package cz.fit.cvut.pidbackend.Model;


public enum VehicleType {
    METRO, TRAM, BUS, REGIONALBUS, NIGHTBUS, NIGHTTRAM, TEMPORARYSERVICE, CABLECAR, SCHOOLSERVICE, DISABLEDTRANSPORTSERVICE, CONTRACTEDSERVICE, FERRY, TRAIN, TEMPORARYBUSONTRAINLINE, TEMPORARYTRAM, NIGHTREGIONALBUS, OTHER
}
